### ISSUE TITLE
main_byol.py: No such file or directory

### ISSUE THREAD

**Issue by zkcys001** [LayneH/LEWEL#1]
Hi! 
Thanks for sharing your nice work. But some files seem to be lost, such as main_byol.py

**Comment by LayneH** [comment]
Hi,

Thanks for reporting the bug.
It seems that we provided the wrong file name in the scripts.
You need to use the `main.py` instead.

We have fixed this bug in the [latest commit](https://github.com/LayneH/LEWEL/commit/9832cf62dcf4636851e1440dddee9d128fb884a0).

**Comment by LayneH** [comment]
Closed due to inactivation.
Please feel free to reopen it if you have any further questions.
